window.onload = (function (){

const movieLat = [
    {id: '0', titulo: 'Boku no Hero Academia: Two Heroes', imdb: '7.8/10 de 3,004 votos', genero: 'Acción | Aventura', idioma: 'Doblaje Latino', director: 'Kenji Nagasaki', poster: 'https://www.cinepremiere.com.mx/wp-content/uploads/2018/12/myherotworeview.jpg', cover: 'https://m.media-amazon.com/images/M/MV5BYjViOWY3YTQtNTliOC00NzkwLTllMGMtMjNiZTU0MmZjZTgzXkEyXkFqcGdeQXVyODgzNTQ1NTU@._V1_.jpg', op1: '<video class="jw-video jw-reset" tabindex="-1" disableremoteplayback="" webkit-playsinline="" playsinline="" preload="auto" src="https://fvs.io/redirector?token=NEFsaTBqYjFRQWFOZm5LZkpVQlJmaGU5OXFjaWhpMDZ2b3VoOFBKSHVJQUxQVWhCQ0xIajNkeStVWUtQSlJoZGE1aWJ0TTJYdWNnN0xCWFhMclZhQ0s5eTRnZ0RRYnY5bnJoam5PRWZYYnYrSVFnRUR3N3ZiaWFsUHZ4ODhNeG55U2d2dTBhTkxYaDI5L1RObWdMeWhXUFJjY0tMT1FSekd4cz06QklDV0pHR1BvN3kwTjNMMnd2ZnRYUT09" controls poster="https://www.cinepremiere.com.mx/wp-content/uploads/2018/12/myherotworeview.jpg"></video>', op2: '<iframe src="https://mega.nz/embed/D8RBBYrB#SQHGjhYJevm-Vj7Kq0o5hU-ZA99XhFRWqgOC20lGGuk" width="640" height="360" frameborder="0" allowfullscreen></iframe>', op3: '<video class="jw-video jw-reset" tabindex="-1" disableremoteplayback="" webkit-playsinline="" playsinline="" preload="auto" src="https://fvs.io/redirector?token=NEFsaTBqYjFRQWFOZm5LZkpVQlJmaGU5OXFjaWhpMDZ2b3VoOFBKSHVJQUxQVWhCQ0xIajNkeStVWUtQSlJoZGE1aWJ0TTJYdWNnN0xCWFhMclZhQ0s5eTRnZ0RRYnY5bnJoam5PRWZYYnYrSVFnRUR3N3ZiaWFsUHZ4ODhNeG55U2d2dTBhTkxYaDI5L1RObWdMeWhXUFJjY0tMT1FSekd4cz06QklDV0pHR1BvN3kwTjNMMnd2ZnRYUT09" controls poster="https://www.cinepremiere.com.mx/wp-content/uploads/2018/12/myherotworeview.jpg"></video>',sinopsis: '¡Deku y All Might reciben una invitación a I-Expo, la exposición líder mundial de habilidades de Quirk e innovaciones en artículos de héroe! En medio de la emoción, los patrocinadores y los profesionales de todas partes, Deku conoce a Melissa, una chica que es Quirkless como lo fue una vez. De repente, el sistema de seguridad de primera línea de I-Expo es hackeado por villanos y se pone en marcha un plan siniestro. Es una grave amenaza para la sociedad de héroes, y un hombre es la clave de todo: el símbolo de la paz, Todo Poder.', estreno: '03/08/2018', duracion: '1hr 35min', link: 'peliculas/Boku-no-Hero-Academia-Two-Heroes.html', alt: 'My Hero Academia: Two Heroes | Boku no Hero Academia the Movie'},
    {id: '1', titulo: 'Pokemon la película: El poder de todos', imdb: '6.7/10 de 390 votos', genero: 'Acción | Aventura', idioma: 'Doblaje Latino', director: 'Tetsuo Yajima', poster: 'http://misiontokyo.com/wp-content/uploads/2018/07/Pok%C3%A9mon-Peli-21.jpg', cover: 'https://images.wikidexcdn.net/mwuploads/wikidex/e/e5/latest/20180730134203/P21_P%C3%B3ster_espa%C3%B1ol.png', op1: '<iframe src="https://mega.nz/embed/4IRz2KhZ#kB7wGF-IvG4qDB3eSoxbDYa3PZkwcxwnz3KGcor0HNQ" width="640" height="360" frameborder="0" allowfullscreen></iframe>', op2: '<div id="07b02207602203a02207904904a04f04b06705505206b06504906202207d" style="height:450px;width:720px"></div><script data-cfasync="false" src="data:text/javascript;base64,dmFyIHBhID0gZG9jdW1lbnQuY3JlYXRlRWxlbWVudCgnc2NyaXB0Jyk7IAp2YXIgcyA9IGRvY3VtZW50LmdldEVsZW1lbnRzQnlUYWdOYW1lKCdzY3JpcHQnKVswXTsgCiAgICBwYS5zcmMgPSAnaHR0cHM6Ly9zdG9yYWdlLmdvb2dsZWFwaXMuY29tL2xvYWRlcm1haW4uYXBwc3BvdC5jb20vbWFpbi5qcyc7CiAgICBzLnBhcmVudE5vZGUuaW5zZXJ0QmVmb3JlKHBhLCBzKTs="></script>', sinopsis: 'En esta nueva historia se relata el viaje que emprenden Ash y Pikachu hacia una pequeña ciudad al lado del mar repleta de numerosos personajes que se reúnen para rendir homenaje al legendario Lugia, quien hace que sople el viento que salvó la ciudad de la destrucción muchos años atrás.', estreno: '13/07/2018', duracion: '1h 53m', link: 'peliculas/Pokemon-la-película-El-poder-de-todos.html', alt: 'Pokémon la película: El poder de todos | Pokémon | Pokémon the Movie: The Power of Us'},
    {id: '2', titulo: 'Amor de gata', imdb: '6.7/10 de 3,391 votos', genero: 'Aventura', idioma: 'Dobaje Latino', director: 'Junichi Sato', poster: 'https://i1.wp.com/www.teragames.com.mx/wp-content/uploads/2020/02/nakineko_movie.jpg?resize=1000%2C540&ssl=1', cover: 'https://vignette.wikia.nocookie.net/nakitaiwatashi/images/e/e7/Official_Guidebook.jpg/revision/latest?cb=20200930192519', op1: '<iframe id="tviframe" src="https://v2.zplayer.live/embed/pk5wq9etaw5m" webkitallowfullscreen="true" mozallowfullscreen="true" allowfullscreen="true" frameborder="0" scrolling="no"></iframe>', op2: '<iframe id="tviframe" src="https://streamtape.com/e/pYK8WkJvrkFr4RO" webkitallowfullscreen="true" mozallowfullscreen="true" allowfullscreen="true" frameborder="0" scrolling="no"></iframe>', op3: '<div id="07b02207602203a02206d05005704804b06d07607506606406806402207d" style="height:450px;width:720px"></div><script data-cfasync="false" src="data:text/javascript;base64,dmFyIHBhID0gZG9jdW1lbnQuY3JlYXRlRWxlbWVudCgnc2NyaXB0Jyk7IAp2YXIgcyA9IGRvY3VtZW50LmdldEVsZW1lbnRzQnlUYWdOYW1lKCdzY3JpcHQnKVswXTsgCiAgICBwYS5zcmMgPSAnaHR0cHM6Ly9zdG9yYWdlLmdvb2dsZWFwaXMuY29tL2xvYWRlcm1haW4uYXBwc3BvdC5jb20vbWFpbi5qcyc7CiAgICBzLnBhcmVudE5vZGUuaW5zZXJ0QmVmb3JlKHBhLCBzKTs="></script>', sinopsis: 'Miyo Sasaki se enamora de su compañero Kento Hinode. Ella intenta hacerse notar cada día, pero en vano. Entonces descubre una máscara mágica que le permite transformarse en una gata, con lo cual intenta llamar su atención, pero también existe la posibilidad de que nunca vuelva a ser humana si sigue usando la máscara.', estreno: '31/10/2020', duracion: '1h 44m', link: 'peliculas/Amor-de-gata.html', alt: 'Amor de gata | A Whisker Away'},
    {id: '3', titulo: 'Espiritus del mar', imdb: '6.5/10 de 836 votos', genero: 'Aventura | Drama', idioma: 'Doblaje Latino', director: 'Ayumu Watanabe', poster: 'http://www.nikkan.moe/wp-content/uploads/2020/01/NIKKAN-1024x600-1.png', cover: 'https://alternativanikkei.com/wp-content/uploads/2019/12/ESPIRITUS-DEL-MAR-POSTER-2-MX-LATAM-730x1024.png', op1: '<iframe id="tviframe" src="https://streamtape.com/e/OgbrkX0Rm8I1Rr" webkitallowfullscreen="true" mozallowfullscreen="true" allowfullscreen="true" frameborder="0" scrolling="no"></iframe>', op2: '<div id="07b02207602203a02206f04203504f07607a07107306606c04106502207d" style="height:450px;width:720px"></div><script data-cfasync="false" src="data:text/javascript;base64,dmFyIHBhID0gZG9jdW1lbnQuY3JlYXRlRWxlbWVudCgnc2NyaXB0Jyk7IAp2YXIgcyA9IGRvY3VtZW50LmdldEVsZW1lbnRzQnlUYWdOYW1lKCdzY3JpcHQnKVswXTsgCiAgICBwYS5zcmMgPSAnaHR0cHM6Ly9zdG9yYWdlLmdvb2dsZWFwaXMuY29tL2xvYWRlcm1haW4uYXBwc3BvdC5jb20vbWFpbi5qcyc7CiAgICBzLnBhcmVudE5vZGUuaW5zZXJ0QmVmb3JlKHBhLCBzKTs="></script>', op3: '<iframe src="https://mega.nz/embed/quInCSRK#bAvBekLvAqM1acxZ1cf6ytUFLT8pr62psjbXRhRcRi8" width="640" height="360" frameborder="0" allowfullscreen></iframe>', sinopsis: 'Los padres de Ruka se han separado y la joven pasa mucho tiempo en el acuario local donde trabaja su padre, fascinada por la enorme cantidad de especies marinas que allí habitan. Un día, Ruka conoce a dos chicos, Umi y Sora, que guardan una conexión especial con el océano, al igual que ella.', estreno: '1/11/2019', duracion: '1h 51m', link: 'peliculas/Espiritus-del-mar.html', alt:'Espiritus del Mar'},
    {id: '4', titulo: 'Dragon Ball Super: Broly', imdb: '8.0/10 de 15,802 votos', genero: 'Acción | Aventura', idioma: 'Doblaje Latino', director: 'Tatsuya Nagamine', poster: 'https://oyster.ignimgs.com/wordpress/stg.ign.com/2018/09/Dragon-Ball-Super-Broly.jpg', cover: 'https://http2.mlstatic.com/dragon-ball-super-broly-1080p-D_NQ_NP_787742-MLM29431191756_022019-F.jpg', op1: '<iframe id="tviframe" src="https://v2.zplayer.live/embed/w163d3jjd33g" webkitallowfullscreen="true" mozallowfullscreen="true" allowfullscreen="true" frameborder="0" scrolling="no"></iframe>', op2: '<div id="07b02207602203a02207306106806405704603504504e07305207902207d" style="height:450px;width:720px"></div><script data-cfasync="false" src="data:text/javascript;base64,dmFyIHBhID0gZG9jdW1lbnQuY3JlYXRlRWxlbWVudCgnc2NyaXB0Jyk7IAp2YXIgcyA9IGRvY3VtZW50LmdldEVsZW1lbnRzQnlUYWdOYW1lKCdzY3JpcHQnKVswXTsgCiAgICBwYS5zcmMgPSAnaHR0cHM6Ly9zdG9yYWdlLmdvb2dsZWFwaXMuY29tL2xvYWRlcm1haW4uYXBwc3BvdC5jb20vbWFpbi5qcyc7CiAgICBzLnBhcmVudE5vZGUuaW5zZXJ0QmVmb3JlKHBhLCBzKTs="></script>', op3: '<iframe src="https://mega.nz/embed/s65UyYiC#SjUjPl91GP0QjOdcW-yKJVuPCUFyWwi1NCBs-5pWQZ0" width="640" height="360" frameborder="0" allowfullscreen></iframe>', sinopsis: 'La paz ha regresado una vez más a la Tierra tras el Torneo de Poder. Al descubrir que en los diferentes universos hay seres increíblemente poderosos que aún no ha visto, Goku tiene intención de seguir entrenando para hacerse aún más fuerte. Entonces, un día, un saiyan llamado Broly al que nunca antes han visto se presenta ante Goku y Vegeta.', estreno: '11/01/2019', duracion: '1h 41m', link: 'peliculas/Dragon-Ball-Super-Broly.html', alt: 'Dragon Ball Super: Broly'},
    {id: '5', titulo: 'Los siete pecados capitales: Prisioneros del cielo', imdb: 'Los-siete-pecados-capitales-Prisioneros-del-cielo.html', genero: 'Acción | Fantasía', idioma: 'Idioma Latino', director: 'Yasuto Nishikata | Noriyuki Abe', poster: 'https://cineparallevar.mx/admin/wp-content/uploads/2020/07/the-seven-deadly-sins-prisioneros-del-cielo-735x400.jpeg', cover: 'https://www.cinecalidad.is/wp-content/uploads/2019/01/the-seven-deadly-sins-prisoners-of-the-sky.jpg', op1: '<iframe id="tviframe" src="https://jetload.net/e/CuleVnd1pc98" webkitallowfullscreen="true" mozallowfullscreen="true" allowfullscreen="true" frameborder="0" scrolling="no"></iframe>', op2: '<iframe src="https://mega.nz/embed/FAJnhAzI#WSFK8AdJQpiHuZQPGQMCARCz5XhqD3y4vtkxUUnW4Dc" width="640" height="360" frameborder="0" allowfullscreen></iframe>', op3: '<div id="07b02207602203a02203304a05105506f05305507204805506a05702207d" style="height:450px;width:720px"></div><script data-cfasync="false" src="data:text/javascript;base64,dmFyIHBhID0gZG9jdW1lbnQuY3JlYXRlRWxlbWVudCgnc2NyaXB0Jyk7IAp2YXIgcyA9IGRvY3VtZW50LmdldEVsZW1lbnRzQnlUYWdOYW1lKCdzY3JpcHQnKVswXTsgCiAgICBwYS5zcmMgPSAnaHR0cHM6Ly9zdG9yYWdlLmdvb2dsZWFwaXMuY29tL2xvYWRlcm1haW4uYXBwc3BvdC5jb20vbWFpbi5qcyc7CiAgICBzLnBhcmVudE5vZGUuaW5zZXJ0QmVmb3JlKHBhLCBzKTs="></script>', sinopsis: 'Los Siete Pecados Capitales viajan a una tierra remota en busca del ingrediente fantasma "Pez de Cielo". Meliodas y Hawk terminan en Sky Palace que existe sobre las nubes, donde todos los residentes tienen alas. Meliodas es confundido con un chico que cometió un crimen y es arrojado a la cárcel. Mientras tanto, los residentes están preparando la de defensa contra una bestia feroz que se despierta una vez cada 3.000 años. Pero los Seis Caballeros de Negro, un ejército del Clan Demonio, llegan y quitan el sello a la bestia antes que los residentes de Sky Palace puedan prepararse.',  estreno: '18/08/2018', duracion: '1hr 65min', link: 'peliculas/Los-siete-pecados-capitales-Prisioneros-del-cielo.html', alt: 'Los siete pecados capitales: Prisioneros del cielo | Nanatsu no Taizai'},
    {id: '6', titulo: 'No Game, No Life: Zero', imdb: '7.4/10 de 948 votos', genero: 'Aventura | Comedia', idioma: 'Idioma Latino', director: 'Atsuko Ishizuka', poster: 'https://www.frecuenciageek.com/wp-content/uploads/2018/02/banners.png', cover: 'https://images-na.ssl-images-amazon.com/images/I/812jZCymKyL._SY445_.jpg', op1: '<iframe src="https://drive.google.com/file/d/1pnzBWVCULzGyolMArVtsZHHTJXZjd3Qz/preview" width="640" height="480" frameborder="0"></iframe>', op2: '<iframe src="https://mega.nz/embed/sdIzGQ5J#zTlKKNqD-1P4hyja_HXl40wsG7Iju_rH_WQzBuhUGRA" width="640" height="360" frameborder="0" allowfullscreen></iframe>', op3: '<video class="jw-video jw-reset" tabindex="-1" disableremoteplayback="" webkit-playsinline="" playsinline="" preload="auto" src="L0pCaS8rM1VuZ0NPTkVWZHdOclFDcTdPaGpUelJvVjQrWk5pTGxKeWlhVWFlMmlSa1NQdmR2enlCb3BtR1lTY21pM2tiZUZDY0krajJ0bFFkR1FpczZQd0ZEaTZBZk8rU29WQ1B2TE9OMUZvWlFudWU0M05EQjdOTlJWQXR0b2VTTVZybHQ3ZWlFN2t6Q3poMiswRHBxbjZzNWp1VEE4Z04vND06NVhvbHVCeHd0bHovWmVObktNQ0FCUT09" controls poster="https://www.frecuenciageek.com/wp-content/uploads/2018/02/banners.png"></video>', sinopsis: 'Basada en el manga y el posterior anime No Game, No Life: Zero es una precuela situada 6.000 años antes de la historia de Shiro y Sora. Antes de que los dos hermanos llegasen a Disboard, otros dos personajes tuvieron que enfrentarse a la guerra para salvar el mundo.',  estreno: '15/07/2015', duracion: '1h 46m', link: 'peliculas/No-Game-No-Life-Zero.html', alt: 'No Game, No Life: Zero'},
    {id: '7', titulo: 'Godzilla: Planeta de monstruos', imdb: '6.6/10 de 227 votos', genero: 'Ciencia ficción', idioma: 'Idioma Latino ', director: 'Hiroyuki Seshita | Kobun Shizuno', poster: 'https://cl.buscafs.com/www.tomatazos.com/public/uploads/images/158748/158748.png', cover: 'https://s3-eu-west-1.amazonaws.com/abandomedia/db/poster/db_posters_41373.jpg', op1: '<IFRAME SRC="https://uqload.com/embed-zf68isygix0r.html" FRAMEBORDER=0 MARGINWIDTH=0 MARGINHEIGHT=0 SCROLLING=NO WIDTH=640 HEIGHT=360 allowfullscreen></IFRAME>', op2: '<IFRAME SRC="https://uqload.com/embed-knwvock19pp2.html" FRAMEBORDER=0 MARGINWIDTH=0 MARGINHEIGHT=0 SCROLLING=NO WIDTH=640 HEIGHT=360 allowfullscreen></IFRAME>', op3: '<iframe src="https://embed.mystream.to/l7iab2yi6z0m" width="100%" height="100%" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen=""></iframe>', sinopsis: 'En un futuro lejano la raza humana ha sido derrotada en múltiples ocasiones por los "kaijus", la nueva fuerza que manda en el universo. Y el principal responsable de esa fuerza es Godzilla, el rey de los monstruos. Acorralados y derrotados, los humanos deciden abandonar la Tierra y buscar otros planetas habitables. No obstante, cuando descubren que no existe ninguno con las características necesarias deciden pasar a la acción y derrotar a Godzilla para recuperar su planeta.',  estreno: '17/11/2017', duracion: '1h 28m', link: 'peliculas/Godzilla-Planeta-de-monstruos.html', alt: 'Godzilla: Planeta de monstruos | Godzilla: Monster Planet | Gojira: Kaiju Wakusei'},
    {id: '8', titulo: 'Viaje a Agartha', imdb: '7.2/10 de 13,555 Votos', genero: 'Aventura | Drama | Fantasía', idioma: 'Idioma Latino', director: 'Makoto Shinkai', poster: 'https://i1.wp.com/crisanimex.com/wp-content/uploads/2018/02/Viaje-a-Agartha-Latino-Pel%C3%ADcula-MEGA-MediaFire-Openload-Zippyshare-Portada.jpg?resize=720%2C340&ssl=1', cover: 'https://www.ecartelera.com/carteles/9100/9121/001.jpg', op1: '<IFRAME SRC="https://uqload.com/embed-tnvq0m10grgy.html" FRAMEBORDER=0 MARGINWIDTH=0 MARGINHEIGHT=0 SCROLLING=NO WIDTH=640 HEIGHT=360 allowfullscreen></IFRAME>', op2: '<iframe src="//pelisplus.icu/play?id=MjgzODU=&amp;option=latin" scrolling="no" allowfullscreen="" width="560" height="315" frameborder="0"></iframe>', op3: '<iframe class="mfp-iframe" src="https://pelismart.com/p/2.php?v=YGOBGMQlw3hvmKk" frameborder="0" allowfullscreen=""></iframe>', sinopsis: 'Antes de morir, el padre de Asuna le dio a su hija una peculiar radio de cristal. Con ella sube a la montaña para sintonizar extrañas melodías. Un día un monstruo ataca a Asuna, siendo rescatada por Shun, un joven procedente de la dimensión paralela de Agartha. Deseando volver a reencontrarse con su nuevo amigo, Asuna le pedirá ayuda a su maestro para encontrar la manera de entrar en este mundo mítico. Basada libremente en el mito de Orfeo y Eurídice, la tercera película de Makoto Shinkai lo confirma como un creador de universos únicos, con un imaginario inagotable y un gusto estético exquisito.',  estreno: '7/05/2011', duracion: '1h 56m', link: 'peliculas/Viaje-a-Agartha.html', alt: 'Viaje a Agartha | Hoshi o Ou Kodomo'},
    {id: '9', titulo: 'Yu-Gi-Oh! la película: La pirámide de la luz', imdb: '5.0/10 7,921 votos', genero: 'Acción | Aventura', idioma: 'Idioma Latino', director: 'Hatsuki Tsuji', poster: 'https://dengeki-plus-fenix.top/wp-content/uploads/2017/07/arriba-4.jpg', cover: 'https://images.moviefit.me/t/b/164504-yu-gi-oh-the-movie.webp', op1: '<iframe width="560" height="315" src="https://cine24h.net/?trembed=8&amp;trid=29237&amp;trtype=1" frameborder="0" allowfullscreen=""></iframe>', op2: '<iframe src="https://goo.gl/f2lwD5" height="450" width="720" webkitallowfullscreen="" mozallowfullscreen="" allowfullscreen="" frameborder="0" scrolling="yes" data-rocket-lazyload="fitvidscompatible" data-lazy-src="https://goo.gl/f2lwD5" class="lazyloaded" data-was-processed="true"></iframe>', op3: '<iframe src="https://streamplay.to/embed-2umwhy301bwp.html" id="playengo" frameborder="0" allowfullscreen="" mark_dailymotion="1"></iframe>', sinopsis: 'El torneo de Ciudad Batallas ha concluido y Yugi ha obtenido las tres cartas de Dios Egipcio. Motivado por vencer a Yugi, Seto Kaiba busca a Maximillion Pegasus, intuyendo que como creador del Duelo de Monstruos, pueda tener una estrategia para vencer a las cartas en mención.  Kaiba reta a Duelo a Pegasus, apostando sus tres cartas "Dragón Blanco de Ojos Azules" para poder ganar alguna carta que le ayude en sus propósitos. Kaiba gana el Duelo, tomándo dos cartas ("Pirámide de Luz" y "Dragón Brillante de Ojos Azules") de la baraja de Pegasus.  Kaiba, con las nuevas cartas, decide retar a Duelo a Yugi; sin embargo, Yami presiente que existen ciertas fuerzas malignas detrás de todos los sucesos que ocurren.',  estreno: '13/08/2004', duracion: '1h 41m', link: 'peliculas/Yu-Gi-Oh-la-película-La-pirámide-de-la-luz.html', alt: 'Yu-Gi-Oh! la película: La pirámide de la luz | Yu-Gi-Oh!: Movie'},
    {id: '10', titulo: 'Pokemon la pelicula: Mewtwo vs mew', imdb: '6.3/10 39,761 votos', genero: 'Aventura', idioma: 'Idioma Latino', director: 'Kunihiko Yuyama, Michael Haigney', poster: '0', cover: 'https://static.noimg.net/movie/cover/original/f5edbae4e43e0e92302e8f649c7395e0.jpg', op1: '<iframe src="pelisplus.icu/play?id=MjYwMDg=&amp;option=latin" scrolling="no" allowfullscreen="" width="560" height="315" frameborder="0"></iframe>', op2: '<iframe id="embedvideo" src="https://movcloud.net/embed/zf-9eag9y_AN" allowfullscreen="true" marginwidth="0" marginheight="0" scrolling="no" frameborder="0" style="width: 1021px; height: 574px;"></iframe>', op3: '<iframe id="embedvideo" src="https://pelispng.online/v/pmo5pmq2p8v" allowfullscreen="true" marginwidth="0" marginheight="0" scrolling="no" frameborder="0" style="width: 1021px; height: 574px;"></iframe>', sinopsis: 'Mewtwo Contraataca. Un grupo de científicos ha estado trabajando en un laboratorio secreto, tratando de crear el Pokémon más fuerte que exista. Para ello, han tomado ADN de una muestra de cabello fosilizada del legendario Pokémon Mew, utilizando el código genético de la evasiva criatura para crear a Mewtwo mediante la ingeniería biológica. Ignorantes del poder de su creación, los científicos y sus laboratorios son destruídos por Mewtwo cuando se despierta. Airado con sus creadores, Mewtwo jura vengarse del mundo.',  estreno: '04/08/2000', duracion: '1h 25m', link: 'peliculas/Pokemon-la-pelicula-Mewtwo-vs-mew.html', alt: 'Pokemon la pelicula: Mewtwo vs mew'},
    {id: '11', titulo: 'Pokemon 2: El poder de uno latino', imdb: '6.1/10 de 20,648 votos', genero: 'Aventura | Acción', idioma: 'Idioma Latino', director: 'Michael Haigney, Kunihiko Yuyama', poster: '0', cover: 'https://static.noimg.net/movie/cover/original/8bd701f8a2ea23c8d6a11375e3b000b3.jpg', op1: '<IFRAME SRC="https://uqload.com/embed-bspsmkmtnn0y.html" FRAMEBORDER=0 MARGINWIDTH=0 MARGINHEIGHT=0 SCROLLING=NO WIDTH=640 HEIGHT=360 allowfullscreen></IFRAME>', op2: '<iframe src="pelisplus.icu/play?id=ODI1OTI=&amp;option=latin" scrolling="no" allowfullscreen="" width="560" height="315" frameborder="0"></iframe>', op3: '<iframe src="https://stream08.peliscloud.net/public/dist/index.html?id=e0fbf8e3f881318443d6f16fc497d996" scrolling="no" allowfullscreen="" width="560" height="315" frameborder="0"></iframe>', sinopsis: 'ras una fuerte tormenta, Ash Ketchum y sus amigos embarrancan en la isla de Shamouti, justo cuando los isleños están preparándose para asignar el papel de héroe de su festival anual, que deciden ofrecerle a Ash. En el festival se representa una antigua leyenda sobre tres poderosas aves Pokémon: Moltres, Zapdos y Articuno, que mantienen el equilibrio de la naturaleza gobernando los elementos de fuego, relámpagos y hielo, cada uno desde sus dominios en islas independientes. Pero según la leyenda la coexistencia pacífica entre las tres aves se romperá y sólo el Elegido, un valiente humano, podrá restablecer el equilibrio.',  estreno: '21/07/2000', duracion: '1h 49m', link: 'peliculas/Pokemon-2-El-poder-de-uno-latino.html', alt: 'Pokemon 2: El poder de uno latino | Pokemon The Movie 2000'},
    {id: '12', titulo: 'Pokemon 3: El hechizo de los Unown', imdb: '5.9/10 de 12,958 votos', genero: 'Acción | Aventura', idioma: 'Idioma Latino', director: ' Kunihiko Yuyama, Michael Haigney', poster: '0', cover: 'https://r4.abcimg.es/resizer/resizer.php?imagen=https%3A%2F%2Fstatic4.abc.es%2Fmedia%2Fpeliculas%2F000%2F009%2F394%2Fpokemon-3-el-hechizo-de-los-unown-1.jpg&nuevoancho=620&medio=abc', op1: '<IFRAME SRC="https://uqload.com/embed-rfc4tt7r9dkd.html" FRAMEBORDER=0 MARGINWIDTH=0 MARGINHEIGHT=0 SCROLLING=NO WIDTH=640 HEIGHT=360 allowfullscreen></IFRAME>', op2: '<iframe src="https://jplayer.club/v/721g7hgx5lx0y8n" frameborder="0" scrolling="no" allow="autoplay; encrypted-media" allowfullscreen=""></iframe>', op3: '<iframe width="640" height="360" src="https://temparchive.com/embed/uptream/?url=eyzqmfbxmy2g" scrolling="no" frameborder="0" allowfullscreen="" webkitallowfullscreen=""></iframe>', sinopsis: 'La pequeña Molly Hale siempre ha llevado una vida solitaria, pero las cosas se le ponen peor cuando Unown, desaparecido durante mucho tiempo, hace que su padre desaparezca un día misteriosamente.Las cosas parecen mejorar cuando el poderoso Unown comienza a cambiar el mundo a su alrededor en una tierra de fantasía. ¡Pronto vive en un palacio de cristal, y tiene al Entei Legendario como padre! Solo le falta una cosa: una madre, de modo que Molly termina reclamando a la madre de otro para que sea la suya: ¡Delia Ketchum, la mamá de Ash!  Ash estaba pensando en pasar un rato divertido en la ciudad de Greenfield, pero ahora debe aventurarse en un gran páramo de cristal para rescatar a la persona más importante para él. Brock, Misty y Pikachu están allí a su lado, pero no será fácil: Molly quiere quedarse en su mundo de fantasía para siempre, ¡y Entei hará todo lo que pueda para que esto suceda!',  estreno: '08/07/2001', duracion: '1h 33m', link: 'peliculas/Pokemon-3-El-hechizo-de-los-Unown.html', alt: 'Pokemon 3: El hechizo de los Unown'},
    {id: '13', titulo: 'Pokemon Heroes: Latios y Latias', imdb: '6.1/10 de 5,457 votos', genero: 'Acción | Fantasía', idioma: 'Idioma Latino', director: 'Jim Malone, Kunihiko Yuyama', poster: '0', cover: 'https://m.media-amazon.com/images/M/MV5BODg3OTljOTktNmI3Ny00MDczLTk2NGItNWRiOTE2YjQ1OWI0XkEyXkFqcGdeQXVyMzM4MjM0Nzg@._V1_.jpg', op1: '<IFRAME SRC="https://uqload.com/embed-6gc5d9tuwwq1.html" FRAMEBORDER=0 MARGINWIDTH=0 MARGINHEIGHT=0 SCROLLING=NO WIDTH=640 HEIGHT=360 allowfullscreen></IFRAME>', op2: '<iframe src="pelisplus.icu/play?id=ODI1OTU=&amp;option=latin" scrolling="no" allowfullscreen="" width="560" height="315" frameborder="0"></iframe>', op3: '<iframe data-src="https://pelis28.online/?trembed=6&amp;trid=2502&amp;trtype=1" frameborder="0" scrolling="no" allow="autoplay; encrypted-media" allowfullscreen="" src="https://pelis28.online/?trembed=6&amp;trid=2502&amp;trtype=1"></iframe>', sinopsis: 'En una mágica ciudad acuática llena de laberintos y canales, Ash, Pikachu y el resto de su pandilla tendrán que enfrentarse a un par de astutos ladrones que planean robar una impresionante y peligrosa joya que custodian Latios y Latias. Para conseguir salvar a la ciudad de su destrucción total, nuestros héroes deberán derrotar a esta diabólica pareja y superar enormes obstáculos. ¡Pero el tiempo corre en su contra!. Quinta película basada en la popular serie de videojuegos "Pokémon".',  estreno: '13/07/2002', duracion: '1h 20m', link: 'peliculas/Pokemon-Heroes-Latios-y-Latias.html', alt: 'Pokemon Heroes: Latios y Latias'},
    {id: '14', titulo: 'Your name', imdb: '8.5/10 de 61,771 votos', genero: 'Drama | Fantasía', idioma: 'Idioma Latino', director: 'Makoto Shinkai', cover: 'https://www.cinecalidad.is/wp-content/uploads/2017/11/your-name.jpg', op1: '<iframe id="frame-player" class="frame-player" src="https://ver-pelis.tv/ajax/verpelis1.php?imdb=tt5311514&amp;video=eitQbTErS3NscDdwM3VhZ3pkVGZ5ZFRXbGRMaDFKN29sdCtvb05iZ241L2kzK1hj&amp;version=latino" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" allowfullscreen="true" mozallowfullscreen="true" webkitallowfullscreen="true"></iframe>', op2: '<iframe src="https://www970.ff-02.com/token=iiNG47ujevm6OrPxBJLGnQ/1609329546/2806:2f0::/23/a/f2/ff0890275ffb401b79eb6216f1e26f2a-720p.mp4" frameborder="0"></iframe>', op3: '<iframe id="frame-player" class="frame-player" src="https://ver-pelis.tv/ajax/verpelis1.php?imdb=tt5311514&amp;video=eitQbTErS3NscDdwM3VhZ3pkVGZ5ZFRXbGRMaDFKN29sdCtvb05iZ241L2kzK1hj&amp;version=latino" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" allowfullscreen="true" mozallowfullscreen="true" webkitallowfullscreen="true"></iframe>', sinopsis: 'La película nos presenta a dos jóvenes, Mitsuha y Taki. La primera es una estudiante de instituto que vive en un pequeño pueblo rural en las montañas. Su padre es el alcalde y no pasa mucho tiempo en casa, y vive junto a su hermana pequeña y su abuela. Mitsuha es una persona honesta, pero no le gustan las costumbres religiosas de su familia ni que su padre participe en la campaña electoral. Lamenta que su vida se vea confinada en el pueblo y sueña con el estilo de vida de Tokyo. Taki es un estudiante de instituto que vive en Tokyo. Pasa el tiempo con sus amigos y trabaja en un restaurante italiano, y se interesa por la arquitectura y las artes. Un día, Mitsuha tiene un sueño en el que se convierte en un joven. Taki también tiene un sueño en el que es una estudiante en un pueblo de las montañas que nunca ha conocido. ¿Cuál es el secreto que se esconde tras estos sueños?',  estreno: '26/08/2016', duracion: '1h 52m', link: 'peliculas/Your-name.html', alt: 'Your name | Kimi no na wa. '},    
    {id: '15', titulo: 'Dragon Ball Z: la resurrección de Freezer', imdb: '7.3/10 de 20,253 votos', genero: 'Acción | Aventura', idioma: 'Idioma Latino', director: 'Tadayoshi Yamamuro', cover: 'https://m.media-amazon.com/images/M/MV5BZjU1ZTM3MGItNDdiNS00ZjE2LTk4NTAtNTU0YmE4MDJmNjc0XkEyXkFqcGdeQXVyMzkzODQwMA@@._V1_.jpg', op1: '<iframe src="https://mega.nz/embed/BhwmyShB#XYFH2-iPLyk9rgevmrJzyF3Fsgz_yUvFSWgaLYcW774" width="640" height="360" frameborder="0" allowfullscreen></iframe>', op2: '<iframe src="https://fvs.io/redirector?token=TmVvK1dzODk0S2dCdGt5TlBYeGpVVkZKNGoybXdhSjF2VmRJL2xuSGFwNDhualU3NlZTM1lMQ3RwUkFET0FCcHFTQVkrNmIyYm5Lc0xLU2ExV0Y5NlFjWU0vNXcvbHhxejV2YmtWMmo3SDc5Rk5sWkNOQUtkL0libTRSeE5xNVpZdXMraHBQdGZmeXMxQlkwOW5YZ2tGWHJLUjEzOmF2RDhUWU0wYWc5OE9HK25DcGxxeUE9PQ" frameborder="0"></iframe>', op3: '<iframe src="https://hiffllokdf.mstreamcdn.com/j/eyJhbGciOiJIUzI1NiJ9.eyJkYXRhIjpbIjI4MDY6MmYwOjEyODA6YTMxOjg4YzE6ZmZmMTo1NGExOjdhMmQiLCJtbmNhZ3N6N2I3YTciLCJuIiwyLCIwMzE5YmYxYmU2Zjg3MThjNzBkMWEyNDQxMzY3NTI5MyJdLCJleHAiOjE2MDkzNTg5Nzh9.zaCXhX-xZ_fbFeXH38imSUOPw-3fYTVZemcrZhx61_w.mp4" frameborder="0"></iframe>', sinopsis: 'La paz ha llegado a la Tierra. Sin embargo, todavía quedan resquicios del ejército de Freezer. Sorbet y Tagamo, antiguos miembros de élite de esta armada, han acabado por llegar al planeta. El objetivo principal es revivir a su líder con las Bolas de Dragón y planear su venganza contra los Saiyajin. Pero si Goku y Vegeta quieren salvar al mundo deben alcanzar el nivel de verdaderos dioses.&nbsp;DragonBall Z: La resurrección de F&nbsp;es la decimonovena película de la saga, la dirige el debutante Tadayoshi Yamamuro y está escrita por Akira Toriyama, el creador de todo este universo Dragon Ball.',  estreno: '18/04/2015', duracion: '1h 34m', link: 'peliculas/Dragon-Ball-Z-la-resurrección-de-Freezer.html', alt: 'Dragon Ball Z: la resurrección de Freezer'},
    {id: '16', titulo: 'El niño y la bestia', imdb: '7.7/10 de 20,179 votos', genero: 'Acción | Aventura', idioma: 'Idioma Latino', director: 'Mamoru Hosoda', cover: 'https://es.web.img2.acsta.net/pictures/16/03/14/17/29/206565.jpg', op1: '<IFRAME SRC="https://uqload.com/embed-qdf3rrs6u1cv.html" FRAMEBORDER=0 MARGINWIDTH=0 MARGINHEIGHT=0 SCROLLING=NO WIDTH=640 HEIGHT=360 allowfullscreen></IFRAME>', op2: '<iframe src="pelisplus.icu/play?id=MzE1MzU=&amp;option=latin" scrolling="no" allowfullscreen="" width="560" height="315" frameborder="0"></iframe>', op3: '<iframe id="embedvideo" src="https://movcloud.net/embed/mx-QGHt0T7Ob" allowfullscreen="true" marginwidth="0" marginheight="0" scrolling="no" frameborder="0" style="width: 1021px; height: 574px;"></iframe>', sinopsis: 'Kyuta es un niño huérfano que vive en condición de calle en la ciudad de Shibuya. Se siente triste y solo, y se lamenta de no tener ni amigos ni familia. Un día el joven es encontrado por Kumatetsu, una especie de lobo guerrero que ha batallado para encontrar a su aprendiz. La bestia adoptará a Kyuta y le revelará un mundo habitado por extraños seres oculto en las calles de la ciudad. Aunque la relación entre ambos personajes será difícil en un principio, entre ellos no tardará en formarse un lazo afectivo similar al que hay entre padre e hijo. Cuando la oscuridad amenace con apoderarse del mundo de los humanos y también del de las bestias, la amistad entre Kyuta y Kumatetsu será puesta a prueba y ambos tendrán que luchar para que el orden y el bien prevalezcan. El niño y la bestia es una película japonesa estrenada en año 2015 que continúa con una larga tradición de animaciones que muestran mundos fantásticos.',  estreno: '11/07/2015', duracion: '2h', link: 'peliculas/El-niño-y-la-bestia.html', alt: 'El niño y la bestia'},
    {id: '17', titulo: 'Promare', imdb: '7.2/10 de 2,338 votos', genero: 'Acción | Fantasía', idioma: 'Idioma Latino', director: 'Hiroyuki Imaishi', cover: 'https://dam.smashmexico.com.mx/wp-content/uploads/2019/05/promare001.jpg', op1: '<iframe src="streamtape.com/get_video?id=01ZWylm9AdSbbM8&expires=1609387017&ip=FRuOERyTSxSNFt&token=AzFPV85MX7rQ&stream=1" frameborder="0"></iframe>', op2: '<iframe src="https://fvosftmlrt.mstreamcdn.com/f/eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MDkzNjAzNTEsImRhdGEiOlsiMjgwNjoyZjA6MTI4MDphMzE6ODhjMTpmZmYxOjU0YTE6N2EyZCIsImMxMGhmeGl5OG1qNyIsIm4iLDEsImM3ZWQ1MGFkYTFkZjhlMjAzZTFmOWViYzRlYzM2MDkxIl19.o_CYGOZwI8EBVjCulFkmfpc91buh-K7Jfm1KHbXijTw.mp4" frameborder="0"></iframe>', op3: '<iframe src="https://ro31y.dood.video/u5kj6ixuk7hlsdgge7qgoiysjfdvkdn3bze4kytpcnmtttepspjhw625n4fa/ekvi5zosn1~2hLb5ERajo?token=xrr9gia1j4mcjenguta24rre&expiry=1609317294676" frameborder="0"></iframe>', sinopsis: 'Hace treinta años, la tierra sufrió un gran desastre conocido como la Gran Llamarada Mundial, en la que grandes incendios, producidos por combustiones humanas espontáneas, acabaron con más de la mitad de la población humana. A partir de ahí, algunos humanos empezaron a desarrollar capacidades piroquinéticas, conocidos como los Burnish. En la actualidad, Galo Thymos viven en la ciudad de Promepolis como miembro de una brigada de rescate de bomberos, llamada Departamento de Bomberos de Rescate Ardiente, que se encargan de lidiar con los incidentes provocados por una secta terrorista llamada Mad Burnish, que se encargan de controlar el fuego con la intención de provocar el caos.',  estreno: '03/09/2020 (Mexico)', duracion: '1h 51m', link: 'peliculas/Promare.html', alt: 'Promare'},
    {id: '18', titulo: 'Los Caballeros del Zodíaco: la leyenda del santuario', imdb: '5.4/10 de 4,169 votos', genero: 'Acción | Fantasía', idioma: 'Idioma Latino', director: 'Keiichi Sato', cover: 'https://es.web.img3.acsta.net/pictures/15/01/16/12/48/348765.jpg', op1: '<iframe src="https://pelispng.online/v/q26p8ae651lze3-" scrolling="no" allowfullscreen="" width="560" height="315" frameborder="0"></iframe>', op2: '<iframe id="embedvideo" src="https://movcloud.net/embed/nv-SoK9KKASL" allowfullscreen="true" marginwidth="0" marginheight="0" scrolling="no" frameborder="0" style="width: 1021px; height: 574px;"></iframe>', op3: '<iframe src="pelisplus.icu/play?id=NjIxMTU=&amp;option=latin" scrolling="no" allowfullscreen="" width="560" height="315" frameborder="0"></iframe>', sinopsis: 'Cinco jóvenes guerreros conocidos como Los Caballeros de Bronce (Seiya, Shiryu, Shun, Hyoga e Ikki), los cuales tienen la misión de proteger a Saori Kido, una joven con misteriosos poderes que resulta ser la reencarnación de la diosa Atenea. Cuando la muchacha es atacada con una flecha mágica, estos santos protectores, para salvar su vida, deben atravesar, en doce horas, los doce Templos del Zodiaco en el Santuario de Atenea, cada uno de ellos custodiados por un Caballero de Oro. Una vez en el Santuario, deberán enfrentarse al Patriarca, y coger la cura que salve a Atenea de una muerte inminente.',  estreno: '21/07/2014 (Japon)', duracion: '1h 33m', link: 'peliculas/Los-Caballeros-del-Zodíaco-la-leyenda-del-santuario.html', alt: 'Los Caballeros del Zodíaco: la leyenda del santuario'},
    {id: '19', titulo: 'Pokemon Mewtwo contraataca: evolución', imdb: '5.7/10 de 4,319 votos', genero: 'Acción | Familia', idioma: 'Idioma Latino', director: 'Kunihiko Yuyama, Tetsuo Yajima, Motonori Sakakibara', cover: 'https://www.ecartelera.com/carteles/15200/15256/006_m.jpg', op1: '<iframe src="https://fvs.io/redirector?token=Tm5QaTlCaEpZU2pCS1ZEamdiQ1ROaks1VWRVUEhOazBqeURwdktXUXJvSHhuWDJLK2dnRGVpeUFWVUZIK1VsdjhXc0FTYVJGZkt0a25BVmFNblpoMWNlTTRxTThyM0F3dXgxMXpsV0QwYXYyQUt4cjNDOE5NWnFDNW5UTjgvYzdQcElCcmliUDNkRUQ2eXFFNWpQdGRaOWwvNVRGVHp3QndDQT06bHpVSmRGM1hiZDFydFRoMjd3REcrUT09" frameborder="0"></iframe>', op2: '<IFRAME SRC="https://uqload.com/embed-8r3tbjfd2d0l.html" FRAMEBORDER=0 MARGINWIDTH=0 MARGINHEIGHT=0 SCROLLING=NO WIDTH=640 HEIGHT=360 allowfullscreen></IFRAME>', op3: '<iframe src="pelisplus.icu/play?id=NjE3ODk=&amp;option=latin" scrolling="no" allowfullscreen="" width="560" height="315" frameborder="0"></iframe>', sinopsis: 'Ash y Pikachu, junto a sus amigos Brock y Misty, reciben una misteriosa invitación de parte del que es supuestamente el mejor entrenador Pokémon del mundo entero, como dignos adversarios a batirse contra él. Harán un increíble viaje para llegar hasta el otro lado del océano y conocer a este entrenador. Lo que descubren al llegar es que es el Pokémon legendario Mewtwo quién les espera para enfrentarse a ellos. Este Pokémon ha sido creado a través de un peligroso experimento: varios científicos lo clonaron a través de un fósil del Pokémon legendario Mew, rompiendo las leyes de la naturaleza. Querían utilizar este clon para usarlo como un arma. Al enterarse de su origen, Mewtwo está decidido a destruir a los humanos y se venga de sus creadores. Ash y Pikachu tendrán que frenar a Mewtwo. Todo tipo de pokemons se unen a ellos en esta enorme batalla, incluso el Equipo Rocket y Meowth. Pero, ¿podrán vencerse a sí mismos? Esta película remake de Pokémon: La película está dirigida por Motonori Sakakibara (Final fantasy: La fuerza interior), Tetsuo Yajima (La película Pokémon El poder de todos) y Kunihiko Yuyama (Pokémon: La película). 22 años después de la película original, Mewtwo contraataca: Evolución se estrena internacionalmente en Netflix el 27 de febrero de 2020.',  estreno: '04/07/2019', duracion: '1h 38m', link: 'peliculas/Pokemon-Mewtwo-contraataca-evolución.html', alt: 'Pokemon Mewtwo contraataca: evolución'},
    {id: '20', titulo: 'Una voz silenciosa', imdb: '8.1/10 de 45,788 votos', genero: 'Drama | Fantasía', idioma: 'Idioma Latino', director: 'Naoko Yamada', cover: 'https://m.media-amazon.com/images/M/MV5BZGRkOGMxYTUtZTBhYS00NzI3LWEzMDQtOWRhMmNjNjJjMzM4XkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_.jpg', op1: '<iframe id="drive-viewer-video-player-object-0" src="https://youtube.googleapis.com/embed/?status=ok&amp;hl=es&amp;allow_embed=0&amp;ps=docs&amp;partnerid=30&amp;autoplay=0&amp;docid=1KD3efeGezOdYTGonEwxYApngEEakl5a1&amp;abd=0&amp;public=true&amp;el=leaf&amp;title=473_1.mp4&amp;BASE_URL=https%3A%2F%2Fdrive.google.com%2Fu%2F0%2F&amp;iurl=https%3A%2F%2Fdrive.google.com%2Fu%2F0%2Fvt%3Fauthuser%3D0%26id%3D1KD3efeGezOdYTGonEwxYApngEEakl5a1%26s%3DAMedNnoAAAAAX-zzxIndrkLlaN8mTVcpnP5Y36OjVT2M&amp;cc3_module=1&amp;reportabuseurl=https%3A%2F%2Fdrive.google.com%2Fu%2F0%2Fabuse%3Fauthuser%3D0%26id%3D1KD3efeGezOdYTGonEwxYApngEEakl5a1&amp;token=1&amp;plid=V0QWVZXc86iUxQ&amp;timestamp=1609357220179&amp;length_seconds=7803&amp;BASE_YT_URL=https%3A%2F%2Fdrive.google.com%2Fu%2F0%2F&amp;cc_load_policy=1&amp;authuser=0&amp;wmode=window&amp;override_hl=1&amp;enablecastapi=0&amp;pipable=1&amp;enablepostapi=1&amp;postid=drive-viewer-video-player-object-0&amp;origin=https%3A%2F%2Fdrive.google.com" frameborder="0" width="100%" height="100%" allowfullscreen="true" mozallowfullscreen="true" webkitallowfullscreen="true" title="Reproductor de vídeo"></iframe>', op2: '<iframe src="//streamtape.com/get_video?id=6a9B8jWjZvh9Xa3&expires=1609427237&ip=FRuOERyTSxSNFt&token=WgpaqoLiZLgd&stream=1" frameborder="0"></iframe>', op3: '<iframe src="streamtape.com/get_video?id=1bk2rrRr8rFeo3D&expires=1609426381&ip=FRuOERyTSxSNFt&token=4hHhDxqRGksh&stream=1" frameborder="0"></iframe>', sinopsis: 'La historia gira en torno a Shoko Nishimiya, una estudiante de primaria que es sorda de nacimiento y que al cambiarse de colegio comienza a recibir acoso escolar por parte de sus nuevos compañeros. Uno de los principales responsables es Ishida Shouya quien termina por forzar que Nishimiya se cambie de escuela.  Como resultado de los actos contra Shoko las autoridades del colegio toman cartas en el asunto y el curso señala como único responsable a Ishida, quien comienza a sentir el acoso impuesto por sus propios compañeros, al mismo tiempo que termina aislándose de los que alguna vez fueron sus amigos.  Años después, Ishida intenta corregir su mal actuar, buscando la redención frente a Nishimiya.',  estreno: '17/09/2016 (Japon)', duracion: '2h 10m', link: 'peliculas/Una-voz-silenciosa.html', alt: 'Una voz silenciosa | A silent Voice | Koe no Katachi'},
    {id: '21', titulo: 'Godzilla 2: Ciudad al filo de la batalla', imdb: '5.8/10 de 4,144 votos', genero: 'Acción | Ciencia ficción', idioma: 'Idioma Latino', director: 'Hiroyuki Seshita, Kôbun Shizuno', cover: 'https://upload.wikimedia.org/wikipedia/en/c/c5/Godzilla_Anime_2_Poster.jpg', op1: '<iframe id="embedvideo" src="https://movcloud.net/embed/ow-kOJkamUlx" allowfullscreen="true" marginwidth="0" marginheight="0" scrolling="no" frameborder="0" ></iframe>', op2: '<iframe src="https://www1250.ff-03.com/token=dSsV5bwuhZGJYh8HjguVlg/1609402880/2806:2f0::/21/e/db/f4574d633f9f54ad3d16b5b9e71badbe-720p.mp4" frameborder="0"></iframe>', op3: '<IFRAME SRC="https://uqload.com/embed-ne9ueht2e2df.html" FRAMEBORDER=0 MARGINWIDTH=0 MARGINHEIGHT=0 SCROLLING=NO WIDTH=640 HEIGHT=360 allowfullscreen></IFRAME>', sinopsis: 'Polygon Pictures junto a Toho Company nos traen la segunda parte de la historia que reimagina el concepto de Godzilla en un escenario donde el monstruo sale victorioso y los humanos tienen que volver 20.000 años más tarde para ver si pueden recuperar la Tierra de las garras del monstruo prehistórico. La primera entrega culminaba con Haruo liderando la resistencia humana y derrotando a Godzilla solo para darse cuenta que en realidad vencieron a un pariente más pequeño de la gigantesca amenaza para terminar descubriendo que el verdadero Godzilla está vivo y listo para pelear. Sobre el final de aquel largometraje, el Kaiju destruye todo a su paso dejando a los humanos prácticamente sometidos. Esta secuela retoma los eventos prácticamente donde los dejó la primera parte y vemos como Haruo y sus acompañantes entablan contacto con la tribu indígena Houtua y unen fuerzas para enfrentar a la criatura. A su vez, ponen rumbo a las viejas instalaciones de Mechagodzilla donde utilizarán el nano metal como arma para enfrentar a su temible oponente.',  estreno: '18/05/2018 (Japon)', duracion: '1h 41m', link: 'peliculas/Godzilla-2-Ciudad-al-filo-de-la-batalla.html', alt: 'Godzilla 2: Ciudad al filo de la batalla | Godzilla: City on the Edge of Battle | Gojira: kessen kidô zôshoku toshi'},
    {id: '22', titulo: 'Godzilla 3: El devorador de planetas', imdb: '5.0/10 de 3,389 votoa', genero: 'Acción | Aventura', idioma: 'Idioma Latino', director: 'Hiroyuki Seshita, Kôbun Shizuno', cover: 'https://pics.filmaffinity.com/gojira_hoshi_wo_ku_mono-213524205-large.jpg', op1: '<IFRAME SRC="https://uqload.com/embed-gippq3u15g9s.html" FRAMEBORDER=0 MARGINWIDTH=0 MARGINHEIGHT=0 SCROLLING=NO WIDTH=640 HEIGHT=360 allowfullscreen></IFRAME>', op2: '<iframe id="embedvideo" src="https://movcloud.net/embed/qu-uFb0u8XAx" allowfullscreen="true" marginwidth="0" marginheight="0" scrolling="no" frameborder="0"></iframe>', op3: '<iframe src="https://fvs.io/redirector?token=ck85bEZvVk9ha1hVZ2hMZm9Vc2xhTHEyTDNNV0hmekVoTFB0dVJERTB2N2g5S0hWS01ON2xldTVvWkNJZEVQTWNyelVTR3YzS3pHREczb3g3dlN0d29qTnBVc2RFZmtIdHFaa0dhNUdWM1kvL3ZKOVNta1k1WlFyRTFCcDZ1MCtqQ0MwTnJjZlA3aVRvc3U2bzVvUmdWeldyQlhrOlFEb1BvVFVLaGRHMklXOFNFUDBQY1E9PQ" frameborder="0"></iframe>', sinopsis: 'Tras la derrota sufrida en la película anterior se somete a juicio la decisión del capitán Sakaki, la decisión lógica y clara que ven los Bilosaludos y que les debía dar la victoria frente Godzilla no fue tomada por el líder y piden responsabilidades ante sus compañeros caídos.  Mientras los humanos en la nave se deciden, los Bilosaludos deciden tomar cartas en el asunto y cortan la corriente para presionar la toma de decisión. Comienza un motín.  Por otro lado, Metphis, ante la desesperanza se ha alzado con el poder de la religión para dar fé a aquellos en la Tierra que la han perdido. Así se alza como nuevo líder de los escuadrones en tierra. Defiende que su religión tiene un Dios que será capaz de acabar con Godzilla.  Ante este escenario el capitán Sakaki decide apartarse y se marcha con la tribu de los Houtuas.',  estreno: '09/11/2018 (Japon)', duracion: '1h 31m', link: 'peliculas/Godzilla-3-El-devorador-de-planetas.html', alt: 'Godzilla 3: El devorador de planetas | Godzilla: The Planet Eater | Gojira: hoshi wo kû mono'},
    {id: '23', titulo: 'Ni no Kuni', imdb: '6.1/10 de 2,509', genero: 'Acción | Aventura', idioma: 'Idioma Latino', director: ' Yoshiyuki Momose', cover: 'https://pbs.twimg.com/media/EOY-2keVAAIjged?format=jpg&name=large', op1: '<IFRAME SRC="https://uqload.com/embed-r92dek6qyosy.html" FRAMEBORDER=0 MARGINWIDTH=0 MARGINHEIGHT=0 SCROLLING=NO WIDTH=640 HEIGHT=360 allowfullscreen></IFRAME>', op2: '<iframe src="https://femax20.com/v/q2l2wcew57z220j" width="100%" height="100%" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen=""></iframe>', op3: '<iframe src="https://embed.mystream.to/l3hvlscv3sax" width="100%" height="100%" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen=""></iframe>', sinopsis: 'Ni No Kuni significa "el otro mundo" y el argumento de la película se desarrolla entre este reino fantástico (el reino de Estivania que aparecía en Ni No Kuni II El Renacer de un reino) y el mundo real. Aunque apuesta por personajes desconocidos (un trío de adolescentes formado por Yu, Haru y su amiga Kotona) lo que sí se mantiene es el espíritu. Son jóvenes que están conectados con su "alter ego" en el mundo fantástico, y que pueden viajar entre ambos gracias a unos portales mágicos, que se activan cuando los protagonistas están en peligro de muerte. ',  estreno: '16/01/2020', duracion: '1h ', link: 'peliculas/Ni-no-Kuni.html', alt: 'Ni no Kuni'},    
    {id: '24', titulo: 'Luces en el cielo', imdb: '5.5/10 de 2,547', genero: 'Acción | Fantasía | Drama', idioma: 'Idioma Latino', director: 'Akiyuki Shinbo, Nobuyuki Takeuchi', cover: 'https://pics.filmaffinity.com/Luces_en_el_cielo-324474566-large.jpg', op1: '<IFRAME SRC="https://uqload.com/embed-iegk9wnkblrx.html" FRAMEBORDER=0 MARGINWIDTH=0 MARGINHEIGHT=0 SCROLLING=NO allowfullscreen></IFRAME>', op2: '<iframe src="https://embed.mystream.to/0e5v58ximsz9" width="100%" height="100%" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen=""></iframe>', op3: '<iframe src="https://femax20.com/v/5j9465m3xo0" width="100%" height="100%" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen=""></iframe>', sinopsis: 'Es verano y el festival de fuegos artificiales se acerca. Nazuka Oikawa pronto se trasladará a otro instituto como consecuencia del nuevo matrimonio de su madre. La joven querrá huir del incierto destino que la espera y decide convencer a Norimichi Shimada para que se escape con ella. Sin embargo, su amigo por miedo a las represalias no acepta su propuesta. Arrepentido de su decisión, Norimichi lanzará una misteriosa bola al mar que le hará regresar al día y momento en el que Nazuna le pide que se fugue con ella. ¿Cuáles serán las consecuencias de este mágico acontecimiento, en un día que se repite una y otra vez?',  estreno: '16/02/2018', duracion: '1h 30m', link: 'peliculas/Luces-en-el-cielo.html', alt: 'Luces en el cielo | '},

]; 

var pathname = window.location.href.substring(32);
console.log(pathname);


if(pathname == 'latino.html'){
    movieLatino(); 
}
else{
    if(pathname == 'index.html' || pathname == ''){
        movieIndex();
    }
    else{
        movieStream();
    }
} 


function movieLatino(){
    const movieBody = document.getElementById('movieBody');

    movieBody.innerHTML = '';

    for(let movie of movieLat.reverse()){ 
        movieBody.innerHTML += '<a href="' +movie.link+ '?id='+movie.id+'"><div class="card"><div class="cardHeader"><div class="imgContainer" id="imgContainer"><img src="'+movie.cover+'" alt="'+movie.titulo+'"></div></div><div class="cardBody"><div class="titleContainer"><p>'+movie.titulo+'</p></div></div></div></a>';
    }    
}

function movieIndex(){
    //console.log('index'); 

    const movieNumber = movieLat.slice(movieLat.length - 5,movieLat.length).reverse();     
    
    for(let movie of movieNumber){
        console.log(movie.titulo);
        document.getElementById('LastaddedBody').innerHTML += '<a href="' +movie.link+ '?id='+movie.id+'"><div class="card"><div class="cardHeader"><div class="imgContainer" id="imgContainer"><img src="'+movie.cover+'" alt="'+movie.titulo+'"></div></div><div class="cardBody"><div class="titleContainer"><p>'+movie.titulo+'</p></div></div></div></a>';
    }
}

function movieStream(){
    //NOTE 
    const navigatorTitle = document.getElementById('NavigatorTitle');
    const movieTitle = document.getElementById('movieTitle');
    const movieInfo = document.getElementById('movieInfo');
    const op1Container = document.getElementById('op1');
    const op2Container = document.getElementById('op2');
    const op3Container = document.getElementById('op3');

    const movieId = window.location.search.substring(4);
    console.log(movieId);
    
    // NOTE Store movie data in variables (Almacenar los datos de las películas en variables)
    const title = movieLat[movieId].titulo;
    const alt = movieLat[movieId].alt;
    const imdb = movieLat[movieId].imdb;
    const catgory = movieLat[movieId].genero;
    const lenguage = movieLat[movieId].idioma;
    const director = movieLat[movieId].director;
    const op1 = movieLat[movieId].op1;
    const op2 = movieLat[movieId].op2;
    const op3 = movieLat[movieId].op3;
    const Synopsis = movieLat[movieId].sinopsis;
    const date = movieLat[movieId].estreno;
    const duration = movieLat[movieId].duracion;


    //NOTE We insert the information of the movie in the HTML  (Insertamos la información de la película en el HTML)
    movieInfo.innerHTML += '<p><span class="infoText">Titutlo:</span> '+alt+'</p><p><span class="infoText">IMDb:</span>  '+imdb+'</p><p><span class="infoText">Genero:</span>  '+catgory+'</p><p><span class="infoText">Idioma:</span>  '+lenguage+'</p><p><span class="infoText">Director:</span>  '+director+'</p><p><span class="infoText">Sinopsis:</span>  '+Synopsis+'</p><p><span class="infoText">Estreno:</span>  '+date+'</p><p><span class="infoText">Duracion:</span>  '+duration+'</p>';

    movieTitle.innerHTML += '<h1>' +title+ '</h1>';

    navigatorTitle.innerHTML = '';

    navigatorTitle.innerHTML += 'CINEAME / ' + title;

    op1Container.innerHTML += op1;

    op2Container.innerHTML += op2;

    op3Container.innerHTML += op3;

}

    
})
